version: '3.9'

services:
  db:
    image: postgres:15
    container_name: booking-db
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: booking-app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src

  nginx:
    image: nginx:alpine
    container_name: booking-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
